export const GET_INGRIDIENT_BURGER = 'GET_INGRIDIENT_BURGER';
export const GET_INGRIDIENT_CONSTRUCTOR = 'GET_INGRIDIENT_CONSTRUCTOR';
export const GET_INGRIDIENT_MODAL = 'GET_INGRIDIENT_MODAL';
export const DELETE_DATA_MODAL = 'GET_DATA_MODAL';
export const GET_NUMBER_OREDER_MODAL = 'GET_NUMBER_OREDER_MODAL';
