export const SET_INGRIDIENT_BURGER = 'SET_INGRIDIENT_BURGER';
export const SET_INGRIDIENT_CONSTRUCTOR = 'SET_INGRIDIENT_CONSTRUCTOR';
export const SET_INGRIDIENT_MODAL = 'SET_INGRIDIENT_MODAL';
export const DELETE_DATA_MODAL = 'DELETE_DATA_MODAL';
export const REQUEST_NUMBER_OREDER = 'REQUEST_NUMBER_OREDER';

export const STATE_MODAL_WINDOWS_INGRIDIENTS = 'STATE_MODAL_WINDOWS';
export const STATE_MODAL_WINDOWS_ORDER = 'STATE_MODAL_WINDOWS_ORDER';
