export const STATE_MODAL_WINDOWS_ORDER: 'STATE_MODAL_WINDOWS_ORDER' =
  'STATE_MODAL_WINDOWS_ORDER';
export const REQUEST_NUMBER_ORDER: 'REQUEST_NUMBER_OREDER' =
  'REQUEST_NUMBER_OREDER';
export const SET_INGRIDIENT_CONSTRUCTOR: 'SET_INGRIDIENT_CONSTRUCTOR' =
  'SET_INGRIDIENT_CONSTRUCTOR';
export const PLUS_ORDER_SUM: 'PLUS_ORDER_SUM' = 'PLUS_ORDER_SUM';
export const MINUS_ORDER_SUM: 'MINUS_ORDER_SUM' = 'MINUS_ORDER_SUM';
export const ADD_INGRIDIENT: 'ADD_INGRIDIENT' = 'ADD_INGRIDIENT';
export const DELETE_INGRIDIENT: 'DELETE_INGRIDIENT' = 'DELETE_INGRIDIENT';
export const RESET_STATE_INGRIDIENT: 'RESET_STATE_INGRIDIENT' =
  'RESET_STATE_INGRIDIENT';
export const ADD_BUN_CONSTRUCTOR: 'ADD_BUN_CONSTRUCTOR' = 'ADD_BUN_CONSTRUCTOR';
export const MOVING_INGRIDIENT_CONSTRUCTOR: 'MOVING_INGRIDIENT_CONSTRUCTOR' =
  'MOVING_INGRIDIENT_CONSTRUCTOR';