export const REQUEST_INGRIDIENT_BURGER: 'REQUEST_INGRIDIENT_BURGER' =
  'REQUEST_INGRIDIENT_BURGER';
export const ERROR_REQUEST_INGRIDIENT_BURGER: 'ERROR_REQUEST_INGRIDIENT_BURGER' =
  'ERROR_REQUEST_INGRIDIENT_BURGER';
export const STATE_MODAL_WINDOWS: 'STATE_MODAL_WINDOWS' =
  'STATE_MODAL_WINDOWS';
export const DELETE_DATA_MODAL: 'DELETE_DATA_MODAL' = 'DELETE_DATA_MODAL';
export const SET_INGRIDIENT_MODAL: 'SET_INGRIDIENT_MODAL' =
  'SET_INGRIDIENT_MODAL';
export const SET_INGRIDIENT: 'SET_INGRIDIENT' = 'SET_INGRIDIENT';
export const NO_INGRIDIENT: 'NO_INGRIDIENT' = 'NO_INGRIDIENT';