export const SET_USER: 'SET_ACCOUNT' = 'SET_ACCOUNT';
export const LOGOUT_USER: 'LOGOUT_USER' = 'LOGOUT_USER';
export const RESET_PASSWORD: 'RESET_PASSWORD' = 'RESET_PASSWORD';
export const NEW_PASSWORD: 'NEW_PASSWORD' = 'NEW_PASSWORD';
export const UPDATE_USER: 'UPDATE_USER' = 'UPDATE_USER';
export const ERROR_LODING_USER: 'ERROR_LODING_USER' = 'ERROR_LODING_USER';