export const WS_CONNECTION_START_ORDERS_ALL: 'WS_CONNECTION_START_ORDERS_ALL' =
  'WS_CONNECTION_START_ORDERS_ALL';
export const WS_CONNECTION_START_ORDERS_USER: 'WS_CONNECTION_START_ORDERS_USER' =
  'WS_CONNECTION_START_ORDERS_USER';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' =
  'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' =
  'WS_CONNECTION_CLOSED';
export const WS_GET_ORDERS: 'WS_GET_ORDERS' = 'WS_GET_ORDERS';
export const WS_SEND_ORDERS: 'WS_SEND_ORDERS' = 'WS_SEND_ORDERS';
export const WS_SET_SOKET: 'WS_SET_SOKET' = 'WS_SET_SOKET';
